In [1]:
import numpy as np

In [2]:
softmax_outputs = np.array([[0.7,0.1,0.2],[0.1,0.5,0.4],[0.02,0.9,0.08]])
class_targets = [0,1,1]
print(softmax_outputs[range(len(class_targets)), class_targets])

[0.7 0.5 0.9]


In [3]:
negative_log = -np.log(softmax_outputs[range(len(softmax_outputs)), class_targets])
print("Negative log: ", negative_log)

Negative log:  [0.35667494 0.69314718 0.10536052]


In [4]:
average_loss = np.mean(negative_log)
print("Average loss: ", average_loss)

Average loss:  0.38506088005216804


In [5]:
y_true_check = np.array([
    [1,0,0],
    [0,1,0],
    [0,1,0]
])

y_pred_clipped_check = np.array([
    [0.7,0.2,0.1],
    [0.1,0.5,0.4],
    [0.02,0.9,0.08]
])

A = y_true_check*y_pred_clipped_check #Element-wise multiplication
print(A)

[[0.7 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.9 0. ]]


In [6]:
B = np.sum(A, axis=1)
print(B)

[0.7 0.5 0.9]


In [7]:
C = -np.log(B)
print(C)

[0.35667494 0.69314718 0.10536052]


In [8]:
print(np.mean(C))

0.38506088005216804
